apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cubestoreRouter.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.cubestoreRouter.env.var }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  CUBESTORE_S3_BUCKET: {{ required "cubestore.s3.bucket is required" .Values.cubestore.s3.bucket | quote }}
  CUBESTORE_S3_REGION: {{ .Values.cubestore.s3.region | quote }}
  {{- if .Values.cubestore.s3.subPath }}
  CUBESTORE_S3_SUB_PATH: {{ .Values.cubestore.s3.subPath | quote }}
  {{- end }}
