apiVersion: apps/v1
kind: Deployment
metadata:
  name: cube-refresh-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: cube-refresh-worker
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.cubeRefreshWorker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      cubejsApp: cubeRefreshWorker
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        cubejsApp: cubeRefreshWorker
        app.kubernetes.io/component: cube-refresh-worker
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: {{ .Values.cubeRefreshWorker.configmap.name }}
            {{- if .Values.cubeRefreshWorker.secret }}
            - secretRef:
                name: {{ .Values.cubeRefreshWorker.secret.name }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.cubeRefreshWorker.image }}"
          imagePullPolicy: {{ .Values.cubeRefreshWorker.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.cubeRefreshWorker.service.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.cubeRefreshWorker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
