apiVersion: v1
kind: Service
metadata:
  name: cubestore-router
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.cubestoreRouter.service.service_port }}
      targetPort: {{ .Values.cubestoreRouter.service.port }}
      protocol: TCP
      name: tcp-meta
      appProtocol: tcp
    - port: 3030
      targetPort: 3030
      protocol: TCP
      name: http
      appProtocol: http
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql-compat
      appProtocol: tcp
  selector:
    cubejsApp: cubestoreRouter
