name: Helm Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up Helm
        uses: azure/setup-helm@v5.0.0

      - name: Lint charts
        run: helm lint charts/cubejs
